// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movie.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Movie.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20260813065709_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("Movie.Domain.Library.EpisodeProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("ShowId")
                        .HasColumnType("integer")
                        .HasColumnName("show_id");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer")
                        .HasColumnName("season_number");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("integer")
                        .HasColumnName("episode_number");

                    b.Property<DateTime>("WatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("watched_at");

                    b.HasKey("UserId", "ShowId", "SeasonNumber", "EpisodeNumber")
                        .HasName("pk_episode_progress");

                    b.HasIndex("UserId", "ShowId")
                        .HasDatabaseName("episode_progress_user_show_idx");

                    b.ToTable("episode_progress", (string)null);
                });

            modelBuilder.Entity("Movie.Domain.Library.RecommendationFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MediaId")
                        .HasColumnType("integer")
                        .HasColumnName("media_id");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("media_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_recommendation_feedback");

                    b.HasIndex("UserId", "MediaType", "MediaId")
                        .IsUnique()
                        .HasDatabaseName("recommendation_feedback_user_media_key");

                    b.ToTable("recommendation_feedback", (string)null);
                });

            modelBuilder.Entity("Movie.Domain.Library.SavedMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<string[]>("Genres")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("genres");

                    b.Property<string>("ListType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("list_type");

                    b.Property<int>("MediaId")
                        .HasColumnType("integer")
                        .HasColumnName("media_id");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("media_type");

                    b.Property<string>("PosterPath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("poster_path");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<decimal?>("VoteAverage")
                        .HasColumnType("numeric")
                        .HasColumnName("vote_average");

                    b.Property<string>("Year")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_saved_media");

                    b.HasIndex("UserId", "ListType", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("saved_media_user_list_idx");

                    b.HasIndex("UserId", "ListType", "MediaId", "MediaType")
                        .IsUnique()
                        .HasDatabaseName("saved_media_user_list_media_key");

                    b.ToTable("saved_media", (string)null);
                });

            modelBuilder.Entity("Movie.Domain.Library.WatchLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<string[]>("Genres")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("genres");

                    b.Property<int>("MediaId")
                        .HasColumnType("integer")
                        .HasColumnName("media_id");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("media_type");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("PosterPath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("poster_path");

                    b.Property<short?>("Rating")
                        .HasColumnType("smallint")
                        .HasColumnName("rating");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<decimal?>("VoteAverage")
                        .HasColumnType("numeric")
                        .HasColumnName("vote_average");

                    b.Property<DateTime>("WatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("watched_at");

                    b.Property<string>("Year")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_watch_log");

                    b.HasIndex("UserId", "WatchedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("watch_log_user_watched_idx");

                    b.HasIndex("UserId", "MediaType", "MediaId")
                        .HasDatabaseName("watch_log_user_media_idx");

                    b.ToTable("watch_log", null, t =>
                        {
                            t.HasCheckConstraint("watch_log_rating_range", "rating is null or rating between 1 and 10");
                        });
                });

            modelBuilder.Entity("Movie.Domain.Lists.ListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AddedById")
                        .HasColumnType("uuid")
                        .HasColumnName("added_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<string[]>("Genres")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("genres");

                    b.Property<Guid>("ListId")
                        .HasColumnType("uuid")
                        .HasColumnName("list_id");

                    b.Property<int>("MediaId")
                        .HasColumnType("integer")
                        .HasColumnName("media_id");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("media_type");

                    b.Property<string>("PosterPath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("poster_path");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<decimal?>("VoteAverage")
                        .HasColumnType("numeric")
                        .HasColumnName("vote_average");

                    b.Property<string>("Year")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_list_items");

                    b.HasIndex("AddedById")
                        .HasDatabaseName("ix_list_items_added_by_id");

                    b.HasIndex("ListId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("list_items_list_idx");

                    b.HasIndex("ListId", "MediaId", "MediaType")
                        .IsUnique()
                        .HasDatabaseName("list_items_list_media_key");

                    b.ToTable("list_items", (string)null);
                });

            modelBuilder.Entity("Movie.Domain.Lists.ListMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("InvitedById")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by");

                    b.Property<Guid>("ListId")
                        .HasColumnType("uuid")
                        .HasColumnName("list_id");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("member")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_list_members");

                    b.HasIndex("InvitedById")
                        .HasDatabaseName("ix_list_members_invited_by_id");

                    b.HasIndex("ListId", "Status")
                        .HasDatabaseName("list_members_list_idx");

                    b.HasIndex("ListId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("list_members_list_user_key");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("list_members_user_idx");

                    b.ToTable("list_members", (string)null);
                });

            modelBuilder.Entity("Movie.Domain.Lists.ListPoll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<Guid>("ListId")
                        .HasColumnType("uuid")
                        .HasColumnName("list_id");

                    b.HasKey("Id")
                        .HasName("pk_list_polls");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_list_polls_created_by_id");

                    b.HasIndex("ListId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("list_polls_list_idx");

                    b.ToTable("list_polls", (string)null);
                });

            modelBuilder.Entity("Movie.Domain.Lists.ListPollCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ListItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("list_item_id");

                    b.Property<Guid>("PollId")
                        .HasColumnType("uuid")
                        .HasColumnName("poll_id");

                    b.HasKey("Id")
                        .HasName("pk_list_poll_candidates");

                    b.HasIndex("ListItemId")
                        .HasDatabaseName("ix_list_poll_candidates_list_item_id");

                    b.HasIndex("PollId", "ListItemId")
                        .IsUnique()
                        .HasDatabaseName("list_poll_candidates_poll_item_key");

                    b.ToTable("list_poll_candidates", (string)null);
                });

            modelBuilder.Entity("Movie.Domain.Lists.ListPollVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PollId")
                        .HasColumnType("uuid")
                        .HasColumnName("poll_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_list_poll_votes");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("ix_list_poll_votes_candidate_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_list_poll_votes_user_id");

                    b.HasIndex("PollId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("list_poll_votes_poll_user_key");

                    b.ToTable("list_poll_votes", (string)null);
                });

            modelBuilder.Entity("Movie.Domain.Lists.MediaList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("join_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_lists");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("lists_created_by_idx");

                    b.HasIndex("JoinCode")
                        .IsUnique()
                        .HasDatabaseName("lists_join_code_key");

                    b.ToTable("lists", null, t =>
                        {
                            t.HasCheckConstraint("lists_name_length", "char_length(btrim(name)) between 1 and 60");
                        });
                });

            modelBuilder.Entity("Movie.Domain.Users.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("AvatarSeed")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("avatar_seed");

                    b.Property<string>("AvatarVariant")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("beam")
                        .HasColumnName("avatar_variant");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.Property<string>("WatchRegion")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("watch_region");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("users_email_idx");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("users_user_name_key");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Movie.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Movie.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Movie.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("Movie.Domain.Library.EpisodeProgress", b =>
                {
                    b.HasOne("Movie.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_episode_progress_users_user_id");
                });

            modelBuilder.Entity("Movie.Domain.Library.RecommendationFeedback", b =>
                {
                    b.HasOne("Movie.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recommendation_feedback_users_user_id");
                });

            modelBuilder.Entity("Movie.Domain.Library.SavedMedia", b =>
                {
                    b.HasOne("Movie.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_media_users_user_id");
                });

            modelBuilder.Entity("Movie.Domain.Library.WatchLogEntry", b =>
                {
                    b.HasOne("Movie.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_watch_log_users_user_id");
                });

            modelBuilder.Entity("Movie.Domain.Lists.ListItem", b =>
                {
                    b.HasOne("Movie.Domain.Users.ApplicationUser", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_list_items_users_added_by_id");

                    b.HasOne("Movie.Domain.Lists.MediaList", "List")
                        .WithMany("Items")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_list_items_lists_list_id");

                    b.Navigation("AddedBy");

                    b.Navigation("List");
                });

            modelBuilder.Entity("Movie.Domain.Lists.ListMember", b =>
                {
                    b.HasOne("Movie.Domain.Users.ApplicationUser", "InvitedBy")
                        .WithMany()
                        .HasForeignKey("InvitedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_list_members_users_invited_by_id");

                    b.HasOne("Movie.Domain.Lists.MediaList", "List")
                        .WithMany("Members")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_list_members_lists_list_id");

                    b.HasOne("Movie.Domain.Users.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_list_members_users_user_id");

                    b.Navigation("InvitedBy");

                    b.Navigation("List");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Movie.Domain.Lists.ListPoll", b =>
                {
                    b.HasOne("Movie.Domain.Users.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_list_polls_users_created_by_id");

                    b.HasOne("Movie.Domain.Lists.MediaList", "List")
                        .WithMany("Polls")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_list_polls_lists_list_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("List");
                });

            modelBuilder.Entity("Movie.Domain.Lists.ListPollCandidate", b =>
                {
                    b.HasOne("Movie.Domain.Lists.ListItem", "ListItem")
                        .WithMany()
                        .HasForeignKey("ListItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_list_poll_candidates_list_items_list_item_id");

                    b.HasOne("Movie.Domain.Lists.ListPoll", "Poll")
                        .WithMany("Candidates")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_list_poll_candidates_list_polls_poll_id");

                    b.Navigation("ListItem");

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("Movie.Domain.Lists.ListPollVote", b =>
                {
                    b.HasOne("Movie.Domain.Lists.ListPollCandidate", "Candidate")
                        .WithMany("Votes")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_list_poll_votes_list_poll_candidates_candidate_id");

                    b.HasOne("Movie.Domain.Lists.ListPoll", "Poll")
                        .WithMany()
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_list_poll_votes_list_polls_poll_id");

                    b.HasOne("Movie.Domain.Users.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_list_poll_votes_users_user_id");

                    b.Navigation("Candidate");

                    b.Navigation("Poll");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Movie.Domain.Lists.MediaList", b =>
                {
                    b.HasOne("Movie.Domain.Users.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lists_users_created_by_id");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Movie.Domain.Lists.ListPoll", b =>
                {
                    b.Navigation("Candidates");
                });

            modelBuilder.Entity("Movie.Domain.Lists.ListPollCandidate", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Movie.Domain.Lists.MediaList", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Members");

                    b.Navigation("Polls");
                });
#pragma warning restore 612, 618
        }
    }
}
